AllCops:
  TargetRubyVersion: 3.0

Metrics:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ExplicitBlockArgument:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Layout/LineLength:
  Max: 120
